### ISSUE TITLE
Content-Type가 application/x-www-form-urlencoded 일때에만 동작하나요?

### ISSUE THREAD

**Issue by Pyohwan** [naver/lucy-xss-filter#10]
안녕하세요. 
네이버의 xssEscapeServletFilter 를 사용중입니다.
테스트 하다 보니 requestHeader의 Content-Type에 따라 적용되느냐 안되느냐로 결정되는것 같습니다.
먼저 application/x-www-form-urlencoded 일경우에는 잘 동작을 합니다.
하지만 multipart/form-data 나 application/json의 경우에는 xssEscapeServletFilter가 동작을 안합니다.
application/json 의 경우에는 Jackson2ObjectMapperFactoryBean에서 modulesToInstall을 통해 해결을 했습니다만, multipart/form-data 의 경우에는 어떻게 해야 할지 감이 안잡히는데요.
최후의 보루로 Request Data들을 일일히 XssPreventer.escape() 해주는것 밖에 없는데
이것이 최선인지 궁금합니다.
감사합니다.

**Comment by leeplay** [comment]
안녕하세요 
lucy-xss-servlet-filter를 말씀하시는거죠 ?

문의하신 두 가지 경우에는 현재는 지원을 안하고 있습니다. (준비 중이기는 한데 ...)
최후에 보루로 선택하신 방법이 최선이긴 합니다. ^^;;; (주어진 제약조건에서 잘 사용하셨습니다.)

참고로 아래는 xssEscapeServletFilter가 필터링을 수행하는 시점입니다. 
```
Q: Filtering 시점은 언제인가요 ?
A: URL 호출 시점이 아닌 서버코드에서 parameter 값을 획득하는 ServletRequest의 getParameter(), getParameterValues(), getParameterMap() 호출 시 필터링을 진행합니다. 
```

아래는 유사 질문입니다. (이 분도 Pyohwan님처럼 필터링 api를 직접 수행하는 방법을 택하고 있습니다. )
- https://github.com/naver/lucy-xss-servlet-filter/issues/4
