### ISSUE TITLE
a 요소의 target 속성

### ISSUE THREAD

**Issue by KimKiHun** [naver/lucy-xss-filter#11]
안녕하세요.

lucy-xss-filter 설정을 default로 사용 중에 a 요소의 target 속성이 제거되어서 확인해 본 결과

lucy-xss-default.xml 의 a 요소의 속성 화이트 리스트에 <ref name="target"/> 이 없어서 삭제되는 것을 확인하고 lucy 설정 파일에 element a 부분을 오버라이드 했는데요. 

해당 속성(target)가 화이트리스트에 추가 안 된 이유를 알 수 있을까요?

**Comment by leeplay** [comment]
@KimKiHun 님

먼저 레포팅 감사합니다. 
하도 오래전 커밋이라 추적하는데 시간이 좀 걸렸습니다. 
아마 누락이 된 채로 올라갔을거라는 의견이 좀 더 많은데요 
패채 대상이면 패치를 하도록 하겠습니다. 

@benelog 님

확인을 해봤는데 최초 커밋에 누락된 채로 커밋이 되었습니다. 

![2016-08-05 16 27 01](https://cloud.githubusercontent.com/assets/7857613/17429474/b528a6dc-5b29-11e6-82be-64abeebec01b.png)

왜 누락이 되었는지 기존 담당자인 재희님께 확인을 해봤는데요 
아래 세 가지 의견을 주었습니다. 

1. 파일 작성당시 HTML 표준이었으면 파일에 선언이 되어있을거다. 표준인데 선언이 안되어 있다면 누락이 됐을 수도 있다. 
2. 해당 필터를 주로 사용하는 팀에서 제외 요구사항을 냈을 수도 있다. 
3. 보안팀에 해당 속성 추가하겠다고 의견을 보내는 것도 나쁘진 않을 거 같다.

감사합니다.
