### ISSUE TITLE
XssFilter와 XssSaxFilter의 차이가 무엇인가요?

### ISSUE THREAD

**Issue by mmyyhh** [naver/lucy-xss-filter#12]
초보라 그런지 메뉴얼을 열심히 읽어봤는데도 차이를 잘 모르겠네요. 무슨 차이가 있나요?

**Comment by leeplay** [comment]
안녕하세요 

간단히 html 문자열을 파싱할 때 DOM과 SAX방식의 차이점과 메모리 사용량 위주로 이해하시면 될 거 같습니다.

#### XssSaxFilter의 등장배경

- XSS Filter 1.2.0 버전부터는 OOM 및 StackOverflowError 문제를 해결한 개선된 SAX 파서 방식의 필터(XssSaxFilter 클래스)를 제공합니다. 
- 물론 XssSaxFilter 또한 여전히 OOM이 발생 가능하지만 메모리 사용량이 대폭 감소하였고,StackOverflowError 는 발생하지 않습니다. 
- 신규로 XSS Filter를 적용하거나 기존에 메모리 이슈가 있으셨던 분들은 SAX 방식의 필터 사용을 권장합니다.

#### XssFilter와 XssSaxFilter와의 차이점

- 아래 링크의 설명이 차이점을 상세히 정리한 내용입니다.
https://github.com/naver/lucy-xss-filter/blob/master/docs/manual/kr/03.%20usage%20guide/3.2%20Using%20the%20XssSaxFilter.md

- 자세히 읽어보셨다고 하시니 좀 더 쉽게 접근 하실려면 XssSaxFilter가 개선형 버전이라 생각하시고 실제 어플리케이션에서 받아들이는 차이점은 아래 두 가지 정도 이해하시면 될 거 같습니다.

![2016-11-30 10 43 05](https://cloud.githubusercontent.com/assets/7857613/20736463/074f0c28-b6ea-11e6-9a0e-8e86f2c2071b.png)

![2016-11-30 10 43 13](https://cloud.githubusercontent.com/assets/7857613/20736464/07532d94-b6ea-11e6-8719-64ca4f0e3016.png)

**Comment by teolex** [comment]
링크가 404 뜨네요...ㅠㅠ

**Comment by Xylus** [comment]
@teolex
안녕하세요,
위 글의 링크는 http://naver.github.io/lucy-xss-filter/kr/#_xsssaxfilter 에서 확인 하실 수 있으며, *4.2.1. 성능과 메모리 사용량* 전후를 요약한 내용입니다.
