### ISSUE TITLE
lucy-xss 적용시 마크업 파서에 관해 문의 드립니다.

### ISSUE THREAD

**Issue by tera0602** [naver/lucy-xss-filter#13]
lucy-xss 적용을하게 되면 다음과 같은 태그를 올바르게 인식하지 않습니다.

ex) <table cellspacing="0"border="0"> 줄임 </table>

이런식으로 속성이 서로 붙어있을때 제대로 수행하지 않는데
 XML specification 에서 정의한 EBNF Notation 과는 조금 상이한 것 같아서 문의드립니다.

수정) 다시 확인해보니 띄어쓰는 것이 표준이 맞네요...
markup.rule 수정하여 해결하엿습니다.

**Comment by tera0602** [comment]
안녕하세요.
실무에 적용해보니 궁금한 점이 있습니다.
네이버 같은경우 사용자 정의 태그인 경우 앞에 x를 넣어서 태그를 만들던데
lucy-xss로 그렇게 구현이 가능할까요?

**Comment by leeplay** [comment]
안녕하세요 

"네이버 같은 경우 사용자 정의 태그인 경우 앞에 x를 넣어서 태그를 만드는데 lucy-xss로 그런 구현이 가능할까요 ?"

질문을 정리하면 사용자 정의 태그를 만들어서 doTag 메소드에서 xss 필터링을 하는게 가능한가란 말씀이신가요 ?
