### ISSUE TITLE
<,> 를허용하고 xss공격방어가 가능한지 문의드립니다.

### ISSUE THREAD

**Issue by glove2** [naver/lucy-xss-filter#14]
먼저
lucy-xss-filter-servlet 필터의 xssPreventerDefender 를 사용하여 프로젝트를 진행하였습니다.
허나 많은 부분에서 <,>,&,",' 의 문자를 필요로 하였습니다. ("1>2 샘플텍스트" 이렇게 입력을 받아야합니다.)
수정페이지에서 input 박스에 ("1 &gt; 2 샘플텍스트") 로 노출이되는것이 문제가 되었습니다.
xssFilter, xssSaxFilter 를 적용할시 에도 html태그가 아닌경우 <,> 는 기본적으로 변환이 됩니다.

최종 질문
<,>,&,",' 를 모두 허용하면서 xss공격 방어가 가능한지 문의드립니다.

p.s
위 질문이 말이 안되는 듯 하지만 혹시나 하여 도움을 구해봅니다.
현 생각으로는 수정페이지 데이터를 가져올때(input box용 데이터)만 하나하나 재 치환하는 방법밖에 모르겠습니다.

**Comment by benelog** [comment]
<, >을 허용하는 정책은 XSS공격이 아니더라도 의도한 HTML의 레이아웃을 깨뜨릴수 있는 위험성이 있습니다.

예를 들어 아래 HTML을 입력한후 Chrome과 Firefox로  열어보면  첫번째 열은 아예 사라지게 됩니다.
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<p> <tes </p>
<p> 2</p>
<p> 3</p>


</body>
</html>
```

JSOUP에서도 테스트해보니 마찬가지의 정책을 택하고 있었습니다.

```java
		String raw = "1 > 2";
		String cleaned = Jsoup.clean(raw, Whitelist.basic());
		System.out.println(cleaned);
```
( 출력결과 `1 &gt; 2`)

**Comment by glove2** [comment]
바쁘신와중에 답변 감사드립니다. 많은 도움이 되었습니다.
