### ISSUE TITLE
XssSaxFilter 적용에 질문있습니다 !! 

### ISSUE THREAD

**Issue by yangbongsoo** [naver/lucy-xss-filter#4]
제가 프로젝트에 Xss Servlet Filter를 적용했는데 게시판에 html태그를 허용해야되는 문제가 생겼습니다. 그래서 삭스필터를 적용하기 위해 
1. lucy-xss-superset-sax.xml 생성 및 작성  
2. lucy-xss-servlet-filter-rule.xml 에서 게시판 부분을 global 필터링 룰 선언으로 필터안되게 설정 
3. 게시판 controller쪽에서 아래와 같이 삭스필터 적용
![gaga](https://cloud.githubusercontent.com/assets/7060510/8878044/e8c17388-3263-11e5-884e-837d923c39b3.PNG)

이렇게 했습니다. 제가 global 필터링 룰을 통해 진행했는데 올바른 방법으로 적용한게 맞는지 궁금합니다 ㅎㅎ (질문이 참 많죠?ㅠㅠ)

**Comment by leeplay** [comment]
global 필터링룰 선언으로 필터 안되게 설정하신 후 controller 소스 내에서 필터링 하셔도 되지만 아래처럼 사용하셔서 추가 코드를 작성하지 않는 걸 추천드립니다. 

```
 <url-rule>
            <url>/url2.do</url>
            <params>
                <param name="cleanQnaContents">
                    <defender>xssSaxFilterDefender</defender>
                </param>
            </params>
        </url-rule>
```

 lucy-xss-superset-sax.xml 파일에는 필터링 할 패턴을 정의하시면 됩니다. 메뉴얼 보시면서 이래저래 문자열 조금씩 변경해가시면서 하시면 될 거 같습니다.  ~

**Comment by leeplay** [comment]
아 저기서 <url>은 yangbongsoo님의 url로 변경하시면 됩니다

**Comment by yangbongsoo** [comment]
url-rule쪽 주석문에 '상위 글로벌 global 설정에 동일한 이름으로 되어있지만 url-rule 설정을 더 우선하여 따른다.'  이걸보고 url-rule이 우선적용되니까 global 필터링 룰을 따로 안해도 되겠구나 생각했습니다. 하지만 테스트 해보니까 global 필터링 룰은 꼭 선언해줘야되더라구요. 

정말 소스코드 변경할 필요가 없어서 좋은거 같아요 감사합니다 ㅎㅎㅎㅎ

**Comment by leeplay** [comment]
한번 디버깅으로 url이 필터링 룰에 설정한 url 과 일치하는지 한번 비교해봐주세요 ~ 
url-rule에 필터링 룰을 설정하면 global에는 설정할 필요는 없거든요 ~  

근데 뭐 의도하신대로 잘동작하고 있다면 굳이 다시 건들일 필요 없이 현재 설정을 유지하는 것도 괜찮겠네요 ^^ 
네 그럼 프로젝트 잘 마무리하세요  ~

**Comment by yangbongsoo** [comment]
제가 8월4일이 완료발표인데 pinpoint까지 적용하려고 도전중이라서
일단 잘 작동하니까 추후에 다시 리팩토링 해보겠습니다 !! 감사합니다
