### ISSUE TITLE
SaxFilter 적용 질문있습니다 version2

### ISSUE THREAD

**Issue by yangbongsoo** [naver/lucy-xss-filter#6]
안녕하세요. SaxFilter적용에 대해서 질문을 드리고 디버깅을 하면서 Spring에 대해서 자세히 몰라 Spring 기초부터 살펴보다가 결국엔 자바 기초부터 다시 보게 되면서 많이 늦었습니다. 

그래서 이제서야 마지막에 말씀해주신 부분에 대해서 다시 시작하려고 하는데요. 
```
보여진 증상만으로 판단하면 호출한 url과 설정한 url이 맞지 않아 보입니다. 
만약 일치하는데 이렇게 동작하면 xss filter의 버그입니다. ;;; 
호출되는 url과 설정된 url을 확인하실 수 있을까요 ???
디버깅 포인트는 XssEscapeFilter 클래스의 doFilter 메소드 입니다. 여기서 인자로 사용하는 url 과 
설정파일에 선언한 url과 100% 일치하는지 한번 확인해주세요 
(디폴트 필터는 설정이 되지 않은 파라메터들의 필터를 수행하지만 파라메터에 특정 필터가 설정되었다면 설정된 필터가 동작해야 합니다.)
``` 

그 문제에 대한 저의 접근법이 타당하고 제가 생각한 부분이 맞는지 글로 논리있게 설명하기엔 아직 실력이 부족합니다. 그래서 실례가 되지 않는다면 다음주 금요일(11월 30일)에 그린팩토리에 다시한번 찾아뵈도 될까요? 제가 학교에 다니는중이라 월~목은 수업을 빠져야해서요 ㅠㅠ

**Comment by leeplay** [comment]
프로젝트 때문에 이제 봤습니다. 
방문일이 헉 11월 30일이 인가요 ? (앞으로 한달 남았군요)  

저도 11월 18일까지는 TF 활동 때문에 굉장히 바쁘네요 ;
그 전은 힘들 거 같구요 
그 이후로 잡아주시면 컨택이 가능할 거 같습니다.

**Comment by yangbongsoo** [comment]
아 제가 글을 잘못썼습니다. ㅠㅠ 다음주 금요일이면 11월 6일이요 !! 근데 18일 까지 바쁘시니 11월 20일날 가능하세요??

**Comment by leeplay** [comment]
넴 그때 연락주세요 ~

**Comment by yangbongsoo** [comment]
20일날 오후 4시에 찾아뵈도 될까요??

**Comment by leeplay** [comment]
아 이번 주는 힘들 거 같습니다;  
다음 주 수요일 이후에 가능하신가요 ???

**Comment by yangbongsoo** [comment]
27일 금요일날 오후 1시에 가능할까요?? ㅎㅎㅎㅎ

**Comment by leeplay** [comment]
넵 괜찮습니다.

**Comment by yangbongsoo** [comment]
그럼 27일날 뵙겠습니다 !!

**Comment by yangbongsoo** [comment]
방금 도착했습니다 1층에서 기다리겠습니다!

**Comment by leeplay** [comment]
동일한 java 파일이 서로 다르게 보였던 건 
제자리서 보니 인텔리제이에서 어떤 java파일을 가져오는 지 보이네요 
한번 확인해보세요 그리그 그 경로에 src폴더가 있는지도요 

그럼 .java가 아니라 .class 경로를 가져오는 의문이 해결이 될 거 같네요

**Comment by yangbongsoo** [comment]
아 오늘 많은 깨달음을 얻고 갑니다. 일하시는데 시간내주셔서 정말 감사드립니다. 

작업한 결과 나오면 올리겠습니다 !!
