### ISSUE TITLE
fieldset 로 감싸면 필터링이 되지 않습니다.

### ISSUE THREAD

**Issue by kdk1026** [naver/lucy-xss-filter#7]
안녕하세요. 
lucy-xss-servlet 다음 버전 사용중입니다.

		<dependency>
		    <groupId>com.navercorp.lucy</groupId>
		    <artifactId>lucy-xss-servlet</artifactId>
		    <version>2.0.0</version>
		</dependency>

제목처럼 fieldset 으로 감싸면 필터링이 되지 않습니다.
text 필드는 확인해보지 않았고, textarea 필드만 확인했습니다.

**Comment by benelog** [comment]
@kdk1026 
이미 해결을 하신건가요?

**Comment by kdk1026** [comment]
제가 잘못봤네요.
멀티파트 인 경우에 문제가 있더라구요.

멀티파트 필터는 multipartResolver 로 해야 오류가 없더라구요.
어쩔 수 없이 파일 업로드 부분만 commons.lang의 escape 수동 처리했습니다.

2015-11-13 4:22 GMT+09:00 Sanghyuk Jung <notifications@github.com>:
